#!/bin/sh

if [ -x /usr/local/opnsense/scripts/sophos_frontpanel/frontpaneld ] && \
   /usr/local/opnsense/scripts/sophos_frontpanel/frontpaneld --is-enabled >/dev/null 2>&1; then
    /usr/local/sbin/configctl sophos_frontpanel start >/dev/null 2>&1 || true
fi
