[start]
command:/usr/local/etc/rc.d/sophos_frontpanel start
parameters:
type:script_output
message:starting Sophos front panel

[stop]
command:/usr/local/etc/rc.d/sophos_frontpanel stop
parameters:
type:script_output
message:stopping Sophos front panel

[restart]
command:/usr/local/etc/rc.d/sophos_frontpanel restart
parameters:
type:script_output
message:restarting Sophos front panel

[status]
command:/usr/local/etc/rc.d/sophos_frontpanel status; exit 0
parameters:
type:script_output
message:query Sophos front panel status

[check]
command:/usr/local/etc/rc.d/sophos_frontpanel check
parameters:
type:script_output
message:check Sophos front panel UART

[list_serial_devices]
command:/usr/local/opnsense/scripts/sophos_frontpanel/list_serial_devices.py
parameters:
type:script_output
message:list available serial devices
