[general]
enabled={{ OPNsense.SophosFrontpanel.general.enabled|default("0") }}
device={{ OPNsense.SophosFrontpanel.general.device|default("/dev/cuau1") }}
title={{ OPNsense.SophosFrontpanel.general.title|default("OPNsense SG330") }}
wan_interfaces={{ OPNsense.SophosFrontpanel.general.wanInterface|default("wan") }}
wan_use_description={{ OPNsense.SophosFrontpanel.general.wanUseDescription|default("1") }}
lan_interfaces={{ OPNsense.SophosFrontpanel.general.lanInterface|default("lan") }}
lan_use_description={{ OPNsense.SophosFrontpanel.general.lanUseDescription|default("1") }}
poll_ms={{ OPNsense.SophosFrontpanel.general.pollMs|default("100") }}
refresh_seconds={{ OPNsense.SophosFrontpanel.general.refreshSeconds|default("2") }}
auto_rotate={{ OPNsense.SophosFrontpanel.general.autoRotate|default("1") }}
rotate_seconds={{ OPNsense.SophosFrontpanel.general.rotateSeconds|default("5") }}
log_level={{ OPNsense.SophosFrontpanel.general.logLevel|default("info") }}
